language: php
sudo: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --diff --dry-run --using-cache=no; fi

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "oV1ysPvbcy1in/ln5nAyVq6EVfTyk9iGrxgUV8cLiD4LZDsEG0PShEt7H8E38gfwkO/uN7KStUJqjg2XjlWThxQzhn/G5RmauXUlsm/ExBoo0TIHVIuWhLzXY3W2eFchsW+l5BveTYr68hk3wp+cRo9rhsXHgPqyVreHoZMbq4w/TJm2cqtUgxsIEWDMgLj2t5S/jrkq2aa87yhyl1MQfyTr7xUvJ8D/MCBnvkmZi1RPWnkoTty272iaCM43jw6MifXmufxriwzOscQX5vFEq1sLwi780JBvdeFdNv+NmBuxNBV/VpgvRJEKLbg2ZGx/kUuy9wsZOxbkPOdqYn8DKN53CeuvKiw/ZLAj8dFQdQJtNjgfNDyGuUBTmjW2B8AvXoMv2jxAlpYr0clNgo/KYzyCuK74L0NE5rRYlmRFm62xOLUZcGR8RPssV9MAe6lCRD/FfPrcwZCP2qCHzYXBx7hvlgxyW65hA/iX9m5W6HRIv7N4Qc92724jDuJWoQizocjv6OY5HBAdiG3EEDWcgWwy6geqtwoj6h586BXlGLA4BYyAb+2/pb6KBo1wc31nfpZV887UhZ+GlV0OoC4nYvjehOWV9q6o/k3HijOm9cHcxVh+yTrhEHsFl6o25V7u6a94LwwMG+dRFOBcltPt6N165Ttxnwsi3hLSVtpmYtM="
